/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.edu.practica05_interface.test.Vista.Disco;
import ec.edu.ups.edu.practica05_interface.test.controlador.ControladorCantante;
import ec.edu.ups.edu.practica05_interface.test.modelo.Cantante;
import ec.edu.ups.edu.practica05_interface.test.modelo.Disco;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jf001
 */
public class VentanaListarDisco extends javax.swing.JInternalFrame {
     private ControladorCantante cantanteControlador;
     private ResourceBundle mensajes;
     private Cantante cantanteTempo;
    /**
     * Creates new form VentanaListarDisco
     */
    public VentanaListarDisco(ControladorCantante cantanteControlador) {
        initComponents();
         this.cantanteControlador = cantanteControlador;
    }
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jblIdBuscarCantante.setText(mensajes.getString("ventana.id"));
        jblNombreBuscarCantante.setText(mensajes.getString("ventana.nombre"));
        jblApellidoBuscarCantante.setText(mensajes.getString("ventana.apellido"));
        jblEdadBuscarCantante.setText(mensajes.getString("ventana.edad"));
        jblSalarioBuscarCantante.setText(mensajes.getString("ventana.salario"));
        jblNacionalidadBuscarCantante.setText(mensajes.getString("ventana.nacionalidad"));
        jblGeneroMusical.setText(mensajes.getString("ventanaCantante.generomusical"));
        jblNumeroConciertosBuscarCantante.setText(mensajes.getString("ventanaCantante.numeroconciertos"));
        jblNumeroGirasBuscarCantante.setText(mensajes.getString("ventanaCantante.numerogiras"));
        jblNumeroSencillosBuscarCantante.setText(mensajes.getString("ventanaCantante.numerosencillos"));
        jblNombreArtisticoBuscarCantante.setText(mensajes.getString("ventanaCantante.nombreartistico"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));
        bntAceptar.setText(mensajes.getString("boton.aceptar"));
        Border borde = BorderFactory.createTitledBorder(mensajes.getString("panel.buscarcantante"));
        jpanelA.setBorder(borde);
        String Codigo = mensajes.getString("txtCodigo");  
        String nombre = mensajes.getString("txtNombre"); 
        String Anio = mensajes.getString("txtAnioLanzamiento");  
        DefaultTableModel modelo = (DefaultTableModel) tblDisco.getModel();
        modelo.setColumnIdentifiers(new Object[]{Codigo,nombre,Anio});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelA = new javax.swing.JPanel();
        jblIdBuscarCantante = new javax.swing.JLabel();
        jblNombreBuscarCantante = new javax.swing.JLabel();
        jblApellidoBuscarCantante = new javax.swing.JLabel();
        jblEdadBuscarCantante = new javax.swing.JLabel();
        jblNacionalidadBuscarCantante = new javax.swing.JLabel();
        jblSalarioBuscarCantante = new javax.swing.JLabel();
        jblNombreArtisticoBuscarCantante = new javax.swing.JLabel();
        jblGeneroMusical = new javax.swing.JLabel();
        jblNumeroSencillosBuscarCantante = new javax.swing.JLabel();
        jblNumeroConciertosBuscarCantante = new javax.swing.JLabel();
        jblNumeroGirasBuscarCantante = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtNombreArtistico = new javax.swing.JTextField();
        txtGeneroMusical = new javax.swing.JTextField();
        txtNumeroSencillos = new javax.swing.JTextField();
        txtNumeroConciertos = new javax.swing.JTextField();
        txtNumeroGiras = new javax.swing.JTextField();
        bntAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisco = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jpanelA.setBackground(new java.awt.Color(0, 153, 153));
        jpanelA.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR CANTANTE"));
        jpanelA.setLayout(null);

        jblIdBuscarCantante.setText("Codigo:");
        jpanelA.add(jblIdBuscarCantante);
        jblIdBuscarCantante.setBounds(130, 30, 100, 16);

        jblNombreBuscarCantante.setText("Nombre:");
        jpanelA.add(jblNombreBuscarCantante);
        jblNombreBuscarCantante.setBounds(133, 67, 58, 16);

        jblApellidoBuscarCantante.setText("Apellido:");
        jpanelA.add(jblApellidoBuscarCantante);
        jblApellidoBuscarCantante.setBounds(130, 110, 58, 16);

        jblEdadBuscarCantante.setText("Edad:");
        jpanelA.add(jblEdadBuscarCantante);
        jblEdadBuscarCantante.setBounds(130, 150, 58, 16);

        jblNacionalidadBuscarCantante.setText("Nacionalidad:");
        jpanelA.add(jblNacionalidadBuscarCantante);
        jblNacionalidadBuscarCantante.setBounds(130, 200, 86, 16);

        jblSalarioBuscarCantante.setText("Salario:");
        jpanelA.add(jblSalarioBuscarCantante);
        jblSalarioBuscarCantante.setBounds(133, 245, 86, 16);

        jblNombreArtisticoBuscarCantante.setText("Nombre Artistico:");
        jpanelA.add(jblNombreArtisticoBuscarCantante);
        jblNombreArtisticoBuscarCantante.setBounds(133, 285, 118, 16);

        jblGeneroMusical.setText("Genero Musical:");
        jpanelA.add(jblGeneroMusical);
        jblGeneroMusical.setBounds(133, 322, 118, 16);

        jblNumeroSencillosBuscarCantante.setText("Numero de Sencillos:");
        jpanelA.add(jblNumeroSencillosBuscarCantante);
        jblNumeroSencillosBuscarCantante.setBounds(133, 362, 118, 16);

        jblNumeroConciertosBuscarCantante.setText("Numero de Conciertos:");
        jpanelA.add(jblNumeroConciertosBuscarCantante);
        jblNumeroConciertosBuscarCantante.setBounds(120, 400, 133, 16);

        jblNumeroGirasBuscarCantante.setText("Numero de Giras:");
        jpanelA.add(jblNumeroGirasBuscarCantante);
        jblNumeroGirasBuscarCantante.setBounds(133, 445, 133, 16);
        jpanelA.add(txtID);
        txtID.setBounds(260, 30, 164, 22);

        txtNombre.setEditable(false);
        txtNombre.setEnabled(false);
        jpanelA.add(txtNombre);
        txtNombre.setBounds(260, 70, 164, 22);

        txtApellido.setEditable(false);
        txtApellido.setEnabled(false);
        jpanelA.add(txtApellido);
        txtApellido.setBounds(260, 110, 164, 22);

        txtEdad.setEditable(false);
        txtEdad.setEnabled(false);
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jpanelA.add(txtEdad);
        txtEdad.setBounds(260, 150, 164, 22);

        txtNacionalidad.setEditable(false);
        txtNacionalidad.setEnabled(false);
        jpanelA.add(txtNacionalidad);
        txtNacionalidad.setBounds(260, 200, 164, 22);

        txtSalario.setEditable(false);
        txtSalario.setEnabled(false);
        jpanelA.add(txtSalario);
        txtSalario.setBounds(260, 240, 164, 22);

        txtNombreArtistico.setEditable(false);
        txtNombreArtistico.setEnabled(false);
        jpanelA.add(txtNombreArtistico);
        txtNombreArtistico.setBounds(260, 280, 164, 22);

        txtGeneroMusical.setEditable(false);
        txtGeneroMusical.setEnabled(false);
        jpanelA.add(txtGeneroMusical);
        txtGeneroMusical.setBounds(260, 320, 164, 22);

        txtNumeroSencillos.setEditable(false);
        txtNumeroSencillos.setEnabled(false);
        jpanelA.add(txtNumeroSencillos);
        txtNumeroSencillos.setBounds(260, 360, 164, 22);

        txtNumeroConciertos.setEditable(false);
        txtNumeroConciertos.setEnabled(false);
        jpanelA.add(txtNumeroConciertos);
        txtNumeroConciertos.setBounds(260, 400, 164, 22);

        txtNumeroGiras.setEditable(false);
        txtNumeroGiras.setEnabled(false);
        jpanelA.add(txtNumeroGiras);
        txtNumeroGiras.setBounds(260, 440, 164, 22);

        bntAceptar.setText("Aceptar");
        bntAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAceptarActionPerformed(evt);
            }
        });
        jpanelA.add(bntAceptar);
        bntAceptar.setBounds(325, 470, 72, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jpanelA.add(btnCancelar);
        btnCancelar.setBounds(415, 470, 76, 23);

        tblDisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Año de Lanzamiento"
            }
        ));
        jScrollPane1.setViewportView(tblDisco);

        jpanelA.add(jScrollPane1);
        jScrollPane1.setBounds(460, 40, 452, 402);
        jpanelA.add(jLabel1);
        jLabel1.setBounds(20, 30, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelA, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        tblDisco.repaint();
        repaint();
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void bntAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAceptarActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.noestalleno"));
        }else{
            cantanteTempo = cantanteControlador.buscarCantante(Integer.parseInt(txtID.getText()));
            System.out.println("Cantantes"+cantanteControlador.verCantantes());

            if (cantanteTempo !=null) {

                txtNombre.setText(cantanteTempo.getNombre());
                txtApellido.setText(cantanteTempo.getApellido());
                txtEdad.setText( String.valueOf(cantanteTempo.getEdad()));
                txtNacionalidad.setText(cantanteTempo.getNacionalidad());
                txtNacionalidad.setText(cantanteTempo.getNacionalidad());
                txtSalario.setText(String.valueOf(cantanteTempo.calcularSalario()));
                txtNombreArtistico.setText(cantanteTempo.getNombreArtistico());
                txtGeneroMusical.setText(cantanteTempo.getGeneroMusical());
                txtNumeroSencillos.setText(String.valueOf( cantanteTempo.getNumeroDeSencillos()));
                txtNumeroConciertos.setText(String.valueOf(cantanteTempo.getNumeroDeConciertos()));
                txtNumeroGiras.setText(String.valueOf(cantanteTempo.getNumeroDeGiras()));
                this.actualizarTabla();

            }else{
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, mensajes.getString("joption.noexiste"));

            }
        }
    }//GEN-LAST:event_bntAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        this.limpiarCampos();
        this.setVisible(false);
        DefaultTableModel modelo = (DefaultTableModel)this.tblDisco.getModel();
        modelo.setNumRows(0);
        this.tblDisco.setModel(modelo);
    }//GEN-LAST:event_btnCancelarActionPerformed
         private void limpiarCampos(){
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtNacionalidad.setText("");
        txtSalario.setText("");
        txtNombreArtistico.setText("");
        txtNumeroConciertos.setText("");
        txtNumeroSencillos.setText("");
        txtNumeroGiras.setText("");
        txtGeneroMusical.setText(""); 
    }
     
    private void actualizarTabla(){
        DefaultTableModel modelo = (DefaultTableModel)this.tblDisco.getModel();
        modelo.setNumRows(0);
        List <Disco> listaDico = cantanteTempo.getDiscos();
        //if (listaPersonas!=null) {
            for (Disco listaDicos : listaDico) {
                int cod = listaDicos.getCodigo();
                if (cod!=0) {
                    String nom = listaDicos.getNombre();
                    int anio = listaDicos.getAnioDeLanzamiento();
                    Object[] rowDate = {cod,nom,anio};
                    modelo.addRow(rowDate);
                }
                
            }
            this.tblDisco.setModel(modelo);
        //}else{
          //  JOptionPane.showMessageDialog(this, "No se ha ingresado ningun cantante aun");
        //}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblApellidoBuscarCantante;
    private javax.swing.JLabel jblEdadBuscarCantante;
    private javax.swing.JLabel jblGeneroMusical;
    private javax.swing.JLabel jblIdBuscarCantante;
    private javax.swing.JLabel jblNacionalidadBuscarCantante;
    private javax.swing.JLabel jblNombreArtisticoBuscarCantante;
    private javax.swing.JLabel jblNombreBuscarCantante;
    private javax.swing.JLabel jblNumeroConciertosBuscarCantante;
    private javax.swing.JLabel jblNumeroGirasBuscarCantante;
    private javax.swing.JLabel jblNumeroSencillosBuscarCantante;
    private javax.swing.JLabel jblSalarioBuscarCantante;
    private javax.swing.JPanel jpanelA;
    private javax.swing.JTable tblDisco;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGeneroMusical;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreArtistico;
    private javax.swing.JTextField txtNumeroConciertos;
    private javax.swing.JTextField txtNumeroGiras;
    private javax.swing.JTextField txtNumeroSencillos;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
