/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.edu.practica05_interface.test.Vista.Cantante;
import ec.edu.ups.edu.practica05_interface.test.controlador.ControladorCantante;
import ec.edu.ups.edu.practica05_interface.test.modelo.Cantante;
import ec.edu.ups.edu.practica05_interface.test.modelo.Disco;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author venot
 */
public class VentanaActualizarCantante extends javax.swing.JInternalFrame {
    private ControladorCantante controladorCantante;
    private List<Disco> listaDiscos;
    private ResourceBundle mensajes;
    /**
     * Creates new form ActualizarCantante
     */
    public VentanaActualizarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
        
    }
    
    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jblIdActualizarCantante.setText(mensajes.getString("ventana.codigo"));
        jblNombreActualizarCantante.setText(mensajes.getString("ventana.nombre"));
        jblApellidoActualizarCantante.setText(mensajes.getString("ventana.apellido"));
        jblEdadActualizarCantante.setText(mensajes.getString("ventana.edad"));
        jblSalarioActualizarCantante.setText(mensajes.getString("ventana.salario"));
        jblNacionalidadActualizarCantante.setText(mensajes.getString("ventana.nacionalidad"));
        jblGeneroMusicalActualizarCantante.setText(mensajes.getString("ventanaCantante.generomusical"));
        jblNumeroConciertosActualizarCantante.setText(mensajes.getString("ventanaCantante.numeroconciertos"));
        jblNumeroGiras.setText(mensajes.getString("ventanaCantante.numerogiras"));
        jblNumeroSencillosActualizarCantante.setText(mensajes.getString("ventanaCantante.numerosencillos"));
        jblNombreArtisticoActualizarCantante.setText(mensajes.getString("ventanaCantante.nombreartistico"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));
        bntActualizar.setText(mensajes.getString("boton.actualizar"));
        bntBuscar.setText(mensajes.getString("boton.buscar")); 
        jpanelAD.setBorder(BorderFactory.createTitledBorder(mensajes.getString("panel.actualizarcantante")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelAD = new javax.swing.JPanel();
        jblIdActualizarCantante = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        bntBuscar = new javax.swing.JButton();
        jblNombreActualizarCantante = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jblApellidoActualizarCantante = new javax.swing.JLabel();
        jblEdadActualizarCantante = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        jblNacionalidadActualizarCantante = new javax.swing.JLabel();
        jblSalarioActualizarCantante = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        txtNombreArtistico = new javax.swing.JTextField();
        jblNombreArtisticoActualizarCantante = new javax.swing.JLabel();
        jblGeneroMusicalActualizarCantante = new javax.swing.JLabel();
        txtGeneroMusical = new javax.swing.JTextField();
        txtNumeroSencillos = new javax.swing.JTextField();
        jblNumeroSencillosActualizarCantante = new javax.swing.JLabel();
        jblNumeroConciertosActualizarCantante = new javax.swing.JLabel();
        txtNumeroConciertos = new javax.swing.JTextField();
        txtNumeroGiras = new javax.swing.JTextField();
        jblNumeroGiras = new javax.swing.JLabel();
        bntActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jpanelAD.setBackground(new java.awt.Color(0, 153, 153));

        jblIdActualizarCantante.setText("Codigo:");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        bntBuscar.setText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });

        jblNombreActualizarCantante.setText("Nombre:");

        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.setEnabled(false);

        jblApellidoActualizarCantante.setText("Apellido:");

        jblEdadActualizarCantante.setText("Edad:");

        txtEdad.setEnabled(false);

        txtNacionalidad.setEnabled(false);

        jblNacionalidadActualizarCantante.setText("Nacionalidad:");

        jblSalarioActualizarCantante.setText("Salario:");

        txtSalario.setEnabled(false);

        txtNombreArtistico.setEnabled(false);

        jblNombreArtisticoActualizarCantante.setText("Nombre Artistico:");

        jblGeneroMusicalActualizarCantante.setText("Genero Musical:");

        txtGeneroMusical.setEnabled(false);

        txtNumeroSencillos.setEnabled(false);

        jblNumeroSencillosActualizarCantante.setText("Numero de Sencillos:");

        jblNumeroConciertosActualizarCantante.setText("Numero de Conciertos:");

        txtNumeroConciertos.setEnabled(false);

        txtNumeroGiras.setEnabled(false);

        jblNumeroGiras.setText("Numero de Giras:");

        bntActualizar.setText("Actualizar");
        bntActualizar.setEnabled(false);
        bntActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelADLayout = new javax.swing.GroupLayout(jpanelAD);
        jpanelAD.setLayout(jpanelADLayout);
        jpanelADLayout.setHorizontalGroup(
            jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelADLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblIdActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(bntBuscar))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblNombreActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblApellidoActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblEdadActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblNacionalidadActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblSalarioActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblNombreArtisticoActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(txtNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblGeneroMusicalActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(txtGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addComponent(jblNumeroSencillosActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(txtNumeroSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addComponent(jblNumeroConciertosActualizarCantante, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(txtNumeroConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addComponent(jblNumeroGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(txtNumeroGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bntActualizar)
                        .addGap(178, 178, 178)
                        .addComponent(btnCancelar)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jpanelADLayout.setVerticalGroup(
            jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelADLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jblIdActualizarCantante))
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscar))
                .addGap(17, 17, 17)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jblNombreActualizarCantante))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jblApellidoActualizarCantante))
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblEdadActualizarCantante)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblNacionalidadActualizarCantante)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblSalarioActualizarCantante)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jblNombreArtisticoActualizarCantante))
                    .addComponent(txtNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jblGeneroMusicalActualizarCantante))
                    .addComponent(txtGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jblNumeroSencillosActualizarCantante))
                    .addComponent(txtNumeroSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jblNumeroConciertosActualizarCantante))
                    .addComponent(txtNumeroConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelADLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jblNumeroGiras))
                    .addComponent(txtNumeroGiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jpanelADLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntActualizar)
                    .addComponent(btnCancelar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelAD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntActualizarActionPerformed
       int id = Integer.parseInt(txtID.getText());
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String nacionalidad = txtNacionalidad.getText();
        double salario = Double.parseDouble(txtSalario.getText());
        String nombreArtistico = txtNombreArtistico.getText();
        String genero = txtGeneroMusical.getText();
        int numeroSencillos = Integer.parseInt(txtNumeroSencillos.getText());
        int numeroConciertos = Integer.parseInt(txtNumeroConciertos.getText());
        int numeroGiras = Integer.parseInt(txtNumeroGiras.getText());
        if (nombre.length()>25 || apellido.length()>25||nacionalidad.length()>25) {
            JOptionPane.showMessageDialog(this, "El nombre ,apellido o apellido es muy largo debe ser menor a 25");
        }else{
            Cantante cantante = new Cantante(llenarEspacio(nombreArtistico), llenarEspacio(genero), numeroSencillos, numeroConciertos, numeroGiras, id, llenarEspacio(nombre), llenarEspacio(apellido), edad, llenarEspacio(nacionalidad), salario);
            cantante.setDiscos(listaDiscos);
            controladorCantante.actualizar(cantante);
            this.limpiarCampos();
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.seactualizoelcantante")); 
            System.out.println(controladorCantante.verCantantes());
            this.visibilidad(false);
            bntActualizar.setEnabled(false);
            this.limpiarCampos();
            bntBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_bntActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        this.setVisible(false);
        this.visibilidad(false);
        bntActualizar.setEnabled(false);
        this.limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
       if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.noestalleno")); 
        }else{
            Cantante cantante = controladorCantante.buscarCantante(Integer.parseInt(txtID.getText()));
            
            if (cantante!=null) {
                this.visibilidad(true);
                txtNombre.setText(cantante.getNombre());
                txtApellido.setText(cantante.getApellido());
                txtEdad.setText( String.valueOf(cantante.getEdad()));
                txtNacionalidad.setText(cantante.getNacionalidad());
                txtNacionalidad.setText(cantante.getNacionalidad());
                txtSalario.setText(String.valueOf(cantante.calcularSalario()));
                txtNombreArtistico.setText(cantante.getNombreArtistico());
                txtGeneroMusical.setText(cantante.getGeneroMusical());
                txtNumeroSencillos.setText(String.valueOf(cantante.getNumeroDeSencillos()));
                txtNumeroConciertos.setText(String.valueOf(cantante.getNumeroDeConciertos()));
                txtNumeroGiras.setText(String.valueOf(cantante.getNumeroDeGiras()));
                bntActualizar.setEnabled(true);
                bntBuscar.setEnabled(false);
                listaDiscos = cantante.getDiscos();
            }else{
                JOptionPane.showMessageDialog(this, mensajes.getString("joption.noexiste")); 
            }
        }
    }//GEN-LAST:event_bntBuscarActionPerformed
    private String llenarEspacio(String palabra){
        StringBuilder nueva = new StringBuilder(palabra);
        for (int i = palabra.length(); i < 25; i++) {
            nueva.append(" ");
        }
        System.out.println("Espacio del caracter :" + nueva.length());
        return nueva.toString();
    }
    
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formInternalFrameActivated

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing
    
    private void visibilidad(boolean variable){
        
        txtID.setEnabled(!variable);
        txtNombre.setEnabled(variable);
        txtApellido.setEnabled(variable);
        txtEdad.setEnabled(variable);
        txtNacionalidad.setEnabled(variable);
        txtSalario.setEnabled(variable);
        txtNombreArtistico.setEnabled(variable);
        txtNumeroConciertos.setEnabled(variable);
        txtNumeroSencillos.setEnabled(variable);
        txtNumeroGiras.setEnabled(variable);
        txtGeneroMusical.setEnabled(variable);
        
    }
    
    private void limpiarCampos(){
        txtID.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtNacionalidad.setText("");
        txtSalario.setText("");
        txtNombreArtistico.setText("");
        txtNumeroConciertos.setText("");
        txtNumeroSencillos.setText("");
        txtNumeroGiras.setText("");
        txtGeneroMusical.setText(""); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntActualizar;
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jblApellidoActualizarCantante;
    private javax.swing.JLabel jblEdadActualizarCantante;
    private javax.swing.JLabel jblGeneroMusicalActualizarCantante;
    private javax.swing.JLabel jblIdActualizarCantante;
    private javax.swing.JLabel jblNacionalidadActualizarCantante;
    private javax.swing.JLabel jblNombreActualizarCantante;
    private javax.swing.JLabel jblNombreArtisticoActualizarCantante;
    private javax.swing.JLabel jblNumeroConciertosActualizarCantante;
    private javax.swing.JLabel jblNumeroGiras;
    private javax.swing.JLabel jblNumeroSencillosActualizarCantante;
    private javax.swing.JLabel jblSalarioActualizarCantante;
    private javax.swing.JPanel jpanelAD;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGeneroMusical;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreArtistico;
    private javax.swing.JTextField txtNumeroConciertos;
    private javax.swing.JTextField txtNumeroGiras;
    private javax.swing.JTextField txtNumeroSencillos;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
