/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.edu.practica05_interface.test.Vista.Compositor;
import ec.edu.ups.edu.practica05_interface.test.controlador.ControladorCompositor;
import ec.edu.ups.edu.practica05_interface.test.modelo.Compositor;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Usuario
 */
public class VentanaEliminarCompositor extends javax.swing.JInternalFrame {
    private ControladorCompositor controladorCompositor;
    private ResourceBundle mensajes;
    /**
     * Creates new form EliminarCompositor
     */
    public VentanaEliminarCompositor(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor = controladorCompositor;
    }

    public void cambiarIdioma(Locale localizacion){
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jblIdEliminarCompositor.setText(mensajes.getString("ventana.id"));
        jblNombreEliminarCompositor.setText(mensajes.getString("ventana.nombre"));
        jblApellidoEliminarCompositor.setText(mensajes.getString("ventana.apellido"));
        jblEdadEliminarCompositor.setText(mensajes.getString("ventana.edad"));
        jblSalarioEliminarCompositor.setText(mensajes.getString("ventana.salario"));
        jblNacionalidadEliminarCompositor.setText(mensajes.getString("ventana.nacionalidad"));
        jblNumeroComposicionesEliminarCompositor.setText(mensajes.getString("ventanaCompositor.numerocomposiciones"));
        btnAceptar.setText(mensajes.getString("boton.buscar"));
        btnEliminarCompositor.setText(mensajes.getString("boton.eliminar"));
        btnCancelar.setText(mensajes.getString("boton.cancelar"));
        Border borde = BorderFactory.createTitledBorder(mensajes.getString("panel.eliminarcompositor"));
        jpanelA.setBorder(borde);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelA = new javax.swing.JPanel();
        jblIdEliminarCompositor = new javax.swing.JLabel();
        jblNombreEliminarCompositor = new javax.swing.JLabel();
        jblApellidoEliminarCompositor = new javax.swing.JLabel();
        jblEdadEliminarCompositor = new javax.swing.JLabel();
        jblNacionalidadEliminarCompositor = new javax.swing.JLabel();
        jblSalarioEliminarCompositor = new javax.swing.JLabel();
        jblNumeroComposicionesEliminarCompositor = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtNumeroComposiciones = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminarCompositor = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jpanelA.setBackground(new java.awt.Color(0, 153, 153));
        jpanelA.setBorder(javax.swing.BorderFactory.createTitledBorder("ELIMINAR COMPOSITOR"));
        jpanelA.setLayout(null);

        jblIdEliminarCompositor.setText("ID:");
        jpanelA.add(jblIdEliminarCompositor);
        jblIdEliminarCompositor.setBounds(60, 38, 14, 16);

        jblNombreEliminarCompositor.setText("Nombre:");
        jpanelA.add(jblNombreEliminarCompositor);
        jblNombreEliminarCompositor.setBounds(60, 67, 47, 16);

        jblApellidoEliminarCompositor.setText("Apellido:");
        jpanelA.add(jblApellidoEliminarCompositor);
        jblApellidoEliminarCompositor.setBounds(60, 101, 47, 16);

        jblEdadEliminarCompositor.setText("Edad:");
        jpanelA.add(jblEdadEliminarCompositor);
        jblEdadEliminarCompositor.setBounds(60, 135, 29, 16);

        jblNacionalidadEliminarCompositor.setText("Nacionalidad:");
        jpanelA.add(jblNacionalidadEliminarCompositor);
        jblNacionalidadEliminarCompositor.setBounds(60, 169, 73, 16);

        jblSalarioEliminarCompositor.setText("Salario:");
        jpanelA.add(jblSalarioEliminarCompositor);
        jblSalarioEliminarCompositor.setBounds(60, 209, 38, 16);

        jblNumeroComposicionesEliminarCompositor.setText("Numero de Composiciones:");
        jpanelA.add(jblNumeroComposicionesEliminarCompositor);
        jblNumeroComposicionesEliminarCompositor.setBounds(60, 243, 148, 16);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jpanelA.add(txtId);
        txtId.setBounds(212, 35, 131, 22);

        txtNombre.setEditable(false);
        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpanelA.add(txtNombre);
        txtNombre.setBounds(212, 64, 131, 22);

        txtApellido.setEditable(false);
        txtApellido.setEnabled(false);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jpanelA.add(txtApellido);
        txtApellido.setBounds(212, 98, 131, 22);

        txtEdad.setEditable(false);
        txtEdad.setEnabled(false);
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jpanelA.add(txtEdad);
        txtEdad.setBounds(212, 132, 131, 22);

        txtNacionalidad.setEditable(false);
        txtNacionalidad.setEnabled(false);
        txtNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalidadActionPerformed(evt);
            }
        });
        jpanelA.add(txtNacionalidad);
        txtNacionalidad.setBounds(212, 166, 131, 22);

        txtSalario.setEditable(false);
        txtSalario.setEnabled(false);
        txtSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioActionPerformed(evt);
            }
        });
        jpanelA.add(txtSalario);
        txtSalario.setBounds(212, 206, 131, 22);

        txtNumeroComposiciones.setEditable(false);
        txtNumeroComposiciones.setEnabled(false);
        txtNumeroComposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroComposicionesActionPerformed(evt);
            }
        });
        jpanelA.add(txtNumeroComposiciones);
        txtNumeroComposiciones.setBounds(214, 240, 131, 22);

        btnAceptar.setText("Buscar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jpanelA.add(btnAceptar);
        btnAceptar.setBounds(371, 35, 72, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jpanelA.add(btnCancelar);
        btnCancelar.setBounds(250, 310, 76, 23);

        btnEliminarCompositor.setText("Eliminar");
        btnEliminarCompositor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCompositorActionPerformed(evt);
            }
        });
        jpanelA.add(btnEliminarCompositor);
        btnEliminarCompositor.setBounds(150, 310, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelA, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadActionPerformed

    private void txtSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioActionPerformed

    private void txtNumeroComposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroComposicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroComposicionesActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.noestalleno")); 
        }else{
            Compositor compositorTempo = controladorCompositor.buscarCompositor(Integer.parseInt(txtId.getText()));
            if (compositorTempo !=null) {
                txtNombre.setText(compositorTempo.getNombre());
                txtApellido.setText(compositorTempo.getApellido());
                txtEdad.setText( String.valueOf(compositorTempo.getEdad()));
                txtNacionalidad.setText(compositorTempo.getNacionalidad());
                txtNacionalidad.setText(compositorTempo.getNacionalidad());
                txtSalario.setText(String.valueOf(compositorTempo.calcularSalario()));
                txtNumeroComposiciones.setText(String.valueOf(compositorTempo.getNumeroDeComposiciones()));

            }else{
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, mensajes.getString("joption.noexiste")); 

            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtId.setText("");
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarCompositorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCompositorActionPerformed
        int respuesta=JOptionPane.showConfirmDialog(this, mensajes.getString("joption.preguntaeliminarcompo")); 
        if (respuesta==JOptionPane.YES_OPTION) {
            controladorCompositor.elimininarCompo(controladorCompositor.buscarCompositor(Integer.parseInt(txtId.getText())));
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.seeliminoelcompo")); 
            txtId.setText("");
            this.limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this, mensajes.getString("joption.noseelimino")); 
        }
    }//GEN-LAST:event_btnEliminarCompositorActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    
    private void limpiarCampos(){
        txtId.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        txtNacionalidad.setText("");
        txtSalario.setText("");
        txtNumeroComposiciones.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarCompositor;
    private javax.swing.JLabel jblApellidoEliminarCompositor;
    private javax.swing.JLabel jblEdadEliminarCompositor;
    private javax.swing.JLabel jblIdEliminarCompositor;
    private javax.swing.JLabel jblNacionalidadEliminarCompositor;
    private javax.swing.JLabel jblNombreEliminarCompositor;
    private javax.swing.JLabel jblNumeroComposicionesEliminarCompositor;
    private javax.swing.JLabel jblSalarioEliminarCompositor;
    private javax.swing.JPanel jpanelA;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroComposiciones;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
